name: deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:
  NODE_VERSION: '18.14.0'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier:check

      - name: Build
        run: npm run build -- --base /my-css-journey/

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
